### ISSUE TITLE
Error on switching songs

### ISSUE THREAD

**Issue by offlinehacker** [matejc/YoutubeDlQueue#1]
While i was switching songs this error occured

```
start: LiaYDPRedWQ
working: LiaYDPRedWQ
done: LiaYDPRedWQ

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: read ECONNRESET
    at errnoException (net.js:904:11)
    at Pipe.onread (net.js:558:19)
```

**Comment by matejc** [comment]
this should be fixed in master now
