### ISSUE TITLE
Error on switching songs 2

### ISSUE THREAD

**Issue by offlinehacker** [matejc/YoutubeDlQueue#6]
This error occured somehow, even if mplayer is in path, after i restarted in same terminal, it works:

```

/home/offlinehacker/projects/YoutubeDlQueue/node_modules/node-ghettoblaster/node-ghettoblaster.js:19
            throw new Error("GBlaster encountered an error or isn't installed.
                  ^
Error: GBlaster encountered an error or isn't installed.
    at /home/offlinehacker/projects/YoutubeDlQueue/node_modules/node-ghettoblaster/node-ghettoblaster.js:19:19
    at ChildProcess.exithandler (child_process.js:652:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Socket.<anonymous> (child_process.js:969:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:465:12)
```

**Comment by matejc** [comment]
I need more data or insert coin.
:)

Probably this one is fixed with https://github.com/matejc/YoutubeDlQueue/commit/1c1e5460d71db65417f5af556bd6b2dbf06c1417
